
name: Documentation Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.PASSWORD }}
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /var/www/documention
            git pull origin main
            yarn install
            pm2 restart 0
            
            
  #pkill -u $USER node
   #         nohup yarn run start > /dev/null 2>&1&
            
            
#pm2 restart 0
